#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/a_update_1.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.0.5

## Scripts
# update ubooquity
service ubooquity stop
cd /tmp
wget http://vaemendis.net/ubooquity/downloads/Ubooquity-1.10.1.zip
unzip Ubooquity-1.10.1.zip
cp Ubooquity.jar /opt/ubooquity/
rm /tmp/Ubooquity-1.10.1.zip

# fix ubooquity out of memory
sed -i 's/^DAEMON_OPTS.*/DAEMON_OPTS="-jar -Xmx512m \/opt\/ubooquity\/Ubooquity.jar -webadmin -headless -port 2022"/' /etc/init.d/ubooquity
systemctl daemon-reload

# missing trusted root certificates
mozroots --import --ask-remove

# fix sub-zero after update
sed -i 's/.*Sub-Zero.bundle.*/git clone https:\/\/github.com\/pannal\/Sub-Zero.bundle \
service plexmediaserver restart/' /opt/openflixr/updateof

# fix landing page offline
sed -i 's/if (data < 1000){.*/if (data < 5000){/' /usr/share/nginx/html/openflixr/index.html

## Let system know update has been installed
touch /opt/update/doneupdate/a_update_1

# Reboot system just to be sure
reboot now
