#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/e_update_5.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.1.3

## Scripts
# improved SSLlabs score with zero drawbacks and improved security
sed -i 's/ssl_protocols.*/ssl_protocols TLSv1.2; ssl_ecdh_curve secp384r1;/' /etc/nginx/sites-enabled/reverse

# set your own ubooquity admin password (comics is default protected so no security issue)
rm /opt/ubooquity/webadmin.cred

## let system know update has been installed
touch /opt/update/doneupdate/e_update_5
