#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/i_update_9.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.2.7
# hotfix for mylar, autosub, NZBhydra
pip uninstall html5lib

## let system know update has been installed
touch /opt/update/doneupdate/i_update_9
