#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/j_update_10.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.2.8
# regression hotfixes
pip uninstall html5lib
pip install lxml
cp /opt/update/updates/openflixr/updateof /opt/openflixr/updateof
chmod +x /opt/openflixr/updateof
cp /opt/update/updates/landingpage/index.html /usr/share/nginx/html/openflixr/index.html
cp /opt/update/updates/landingpage/check.png /usr/share/nginx/html/openflixr/assets/img/check.png

## let system know update has been installed
touch /opt/update/doneupdate/j_update_10
