#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/k_update_11.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.3.0
# (regression) fixes, system updates and cleanup
cp /opt/update/updates/openflixr/apt-get-queue /opt/openflixr/apt-get-queue
cp /opt/update/updates/configs/nginx.conf /etc/nginx/nginx.conf
systemctl add-wants multi-user.target rpcbind.service
bash /opt/openflixr/apt-get-queue linux-virtual
apt-get autoremove --purge linux-generic -y
apt-get remove --purge linux-firmware -y
update-grub
apt-get autoremove --purge x11-utils lxpolkit -y
apt-get autoremove -y
bash /opt/openflixr/apt-get-queue linux-tools-common linux-tools-4.4.0-31-generic
bash /opt/openflixr/apt-get-queue pdns-recursor
pdns_recursor --config
sed -i 's/# forward-zones=/forward-zones=8.8.4.4;8.8.8.8/' /etc/powerdns/recursor.conf
sed -i 's/dns-nameservers.*/dns-nameservers 127.0.0.1/' /etc/network/interfaces
touch /etc/pf_ring/pf_ring.start
sed -i '/swapoff.*/a \
echo noop >\/sys\/block\/sda\/queue\/scheduler\
modprobe msr\
x86_energy_perf_policy performance' /etc/rc.local

# revert netdata 24 hour, back to 1 hour. It was eating too much memory
sed -i 's/history = 86400.*/history = 3600/' /opt/netdata/etc/netdata/netdata.conf

# KSM fix
sed -i 's/echo 1000 >\/sys\/kernel\/mm\/ksm\/sleep_millisecs\/.*/echo 1000 >\/sys\/kernel\/mm\/ksm\/sleep_millisecs/' /etc/rc.local

# add Wetty again
git clone https://github.com/krishnasrinivas/wetty /opt/wetty
cd /opt/wetty
npm install wetty -g
cp /opt/update/updates/configs/wetty.service /lib/systemd/system/wetty.service
systemctl enable wetty.service
service wetty start

sed -i '/# add_config_4/a \
location /wetty {\
    auth_basic off;\
    allow 10.0.0.0/8;\
    allow 172.16.0.0/12;\
    allow 192.168.0.0/16;\
    allow 127.0.0.1;\
    deny all;\
    proxy_pass http://127.0.0.1:4000/wetty;\
    proxy_http_version 1.1;\
    proxy_read_timeout 43200000;\
    proxy_set_header X-Real-IP $remote_addr;\
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\
    proxy_set_header Host $http_host;\
    proxy_set_header X-NginX-Proxy true;\
}\
' /etc/nginx/sites-enabled/reverse

# monit configs
cp /opt/update/updates/monit/wetty /etc/monit/conf.d/wetty
cp /opt/update/updates/monit/wetty /opt/config/monit/wetty

# update updatewkly.sh
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh

## update version
sed -i 's/1.*/1.3.0 Bacchus/' /opt/openflixr/version
sed -i 's/Media Server 1.*/Media Server 1.3.0 <sup>Bacchus<\/sup><\/span>/' /usr/share/nginx/html/openflixr/index.html
crudini --set /usr/share/nginx/html/setup/config.ini custom custom1 1.3.0

## let system know update has been installed
touch /opt/update/doneupdate/k_update_11

# reboot system just to be sure
reboot now
