#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/l_update_12.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.3.7
# system updates and maintenance
tune2fs -c 1 /dev/sda1
apt-get purge php5-memcached libmemcached11:amd64 memcached -y
apt-get autoremove -y
cd /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Data/com.plexapp.system/DataItems/Deactivated/
rm -rf com.plexapp.agents.subzero/
cp /opt/update/updates/configs/jackett.service /etc/systemd/system/jackett.service
systemctl daemon-reload
sed -i '/modprobe msr/d' /etc/rc.local
sed -i '/x86_energy_perf_policy performance/d' /etc/rc.local
cp /usr/share/nginx/html/openflixr/favicon.ico /usr/share/nginx/html/favicon.ico
rm /home/openflixr/.homeassistant/plex.conf

# startup changes
cp /opt/update/updates/openflixr/updateof /opt/openflixr/updateof
chmod +x /opt/openflixr/updateof

# mopidy default music dir
crudini --set /etc/mopidy/mopidy.conf local media_dir /mnt/music

# console messages
cp /opt/update/updates/openflixr/ipaddress /opt/openflixr/ipaddress
chmod +x /opt/openflixr/ipaddress

# plexrequests hotfix
cp /opt/update/updates/openflixr/fixplexrequests /opt/openflixr/fixplexrequests

# maintenance task + update fix
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh
cp /opt/update/updates/openflixr/cleanup.sh /opt/openflixr/cleanup.sh
chmod +x /opt/openflixr/cleanup.sh

# enhanced logging
cp /opt/update/updates/openflixr/logio.sh /opt/openflixr/logio.sh
chmod +x /opt/openflixr/logio.sh

# fix headphones saving settings
service headphones stop
crudini --set /opt/headphones/config.ini General http_proxy 1

# monit configs
cp /opt/update/updates/monit/ntp /etc/monit/conf.d/ntp
cp /opt/update/updates/monit/ntp /opt/config/monit/ntp
cp /opt/update/updates/monit/ssh /etc/monit/conf.d/ssh
cp /opt/update/updates/monit/ssh /opt/config/monit/ssh
cp /opt/update/updates/monit/webmin /etc/monit/conf.d/webmin
cp /opt/update/updates/monit/webmin /opt/config/monit/webmin
cp /opt/update/updates/monit/redis /etc/monit/conf.d/redis
cp /opt/update/updates/monit/redis /opt/config/monit/redis
cp /opt/update/updates/monit/mopidy /etc/monit/conf.d/mopidy
cp /opt/update/updates/monit/mopidy /opt/config/monit/mopidy
cp /opt/update/updates/monit/nfs /etc/monit/conf.d/nfs
cp /opt/update/updates/monit/nfs /opt/config/monit/nfs
cp /opt/update/updates/monit/couchpotato /etc/monit/conf.d/couchpotato
cp /opt/update/updates/monit/couchpotato /opt/config/monit/couchpotato
cp /opt/update/updates/monit/certificate /opt/config/monit/certificate
domain=$(crudini --get /usr/share/nginx/html/setup/config.ini access domainname)
sed -i 's/check host example.com with address example.com/check host '$domain' with address '$domain'/' /opt/config/monit/certificate

## let system know update has been installed
touch /opt/update/doneupdate/l_update_12
