#!/bin/bash
THISUSER=$(whoami)
    if [ $THISUSER != 'root' ]
        then
            echo 'You must use sudo to run this script, sorry!'
           exit 1
    fi

exec 1> >(tee -a /var/log/openflixrupdate/o_update_15.log) 2>&1
TODAY=$(date)
echo "-----------------------------------------------------"
echo "Date:          $TODAY"
echo "-----------------------------------------------------"

## OpenFLIXR Update version 1.6.0
## fixes
rm /etc/monit/conf.d/certificate
rm /etc/monit/conf.d/redis
cp -R /opt/update/latest/* /usr/share/nginx/html/latest
dpkg --configure -a
npm uninstall -g thelounge
systemctl stop lounge
systemctl disable lounge
rm /etc/systemd/system/lounge.service
systemctl daemon-reload
systemctl reset-failed
mkdir /var/log/nginx
mkdir /var/log/spotweb
bash /opt/openflixr/apt-get-queue php-curl
sed -i 's/# write-pid=yes/write-pid=yes/' /etc/powerdns/recursor.conf
sed -i 's/write-pid=no/write-pid=yes/' /lib/systemd/system/pdns-recursor.service
systemctl daemon-reload

# fix letsencryptupdate
cd /opt/letsencrypt
cp cli.ini /opt/openflixr/cli.ini
git fetch --all
git reset --hard origin/master
git pull origin master
cp /opt/openflixr/cli.ini /opt/letsencrypt
rm -rf /home/openflixr/.local/share/letsencrypt/*

# fix Plexrequest.net
service plexrequestsnet stop
cd /tmp/
plexrequestsver=$(wget -q https://github.com/tidusjar/Ombi/releases/latest -O - | grep -E \/tag\/ | awk -F "[<>]" '{print $3}' | cut -c 6-)
wget -q https://github.com/tidusjar/Ombi/releases/download/$plexrequestsver/Ombi.zip
unzip Ombi.zip
rm Ombi.zip
cp /opt/plexrequest.net/PlexRequests.sqlite /opt/openflixr/PlexRequests.sqlite
rm -rf /opt/plexrequest.net/*
cp -r -u Release/* /opt/plexrequest.net/
rm -rf Release/
cp /opt/openflixr/PlexRequests.sqlite /opt/plexrequest.net/PlexRequests.sqlite
sed -i 's/PlexRequests.exe/Ombi.exe/' /etc/systemd/system/plexrequestsnet.service
systemctl daemon-reload
service plexrequestsnet start
cp /opt/update/updates/monit/plexrequests /etc/monit/conf.d/plexrequests
cp /opt/update/updates/monit/plexrequests /opt/config/monit/plexrequests

# script updates
cp /opt/update/updates/openflixr/updateof /opt/openflixr/updateof
chmod +x /opt/openflixr/updateof
cp /opt/update/updates/openflixr/logio.sh /opt/openflixr/logio.sh
chmod +x /opt/openflixr/logio.sh
cp /opt/update/updates/openflixr/cleanup.sh /opt/openflixr/cleanup.sh
chmod +x /opt/openflixr/cleanup.sh
cp /opt/update/updates/openflixr/updatewkly.sh /opt/openflixr/updatewkly.sh
chmod +x /opt/openflixr/updatewkly.sh

# features
bash /opt/openflixr/apt-get-queue mhddfs

# internal server error
mkdir /usr/share/nginx/html/error/500
cp /opt/update/updates/configs/error/500/index.html /usr/share/nginx/html/error/500
sed -i 's/error_page 502 \/error\/502\/index.html;.*/error_page 502 \/error\/502\/index.html;error_page 500 \/error\/500\/index.html;/' /etc/nginx/sites-enabled/reverse

# add letsencrypt auto renew
cp /opt/update/updates/cronjobs/letsrenew.sh /etc/cron.weekly
chmod +x /etc/cron.weekly/letsrenew.sh
chown root:root /etc/cron.weekly/letsrenew.sh

## update version
sed -i 's/1.*/1.6.0 The Story Continues/' /opt/openflixr/version
crudini --set /usr/share/nginx/html/setup/config.ini custom custom1 1.6.0

## let system know update has been installed
touch /opt/update/doneupdate/o_update_15

# reboot system just to be sure
reboot now
